version: '3.7'

services:
  php-base:
    image: docker.io/dofroscra/php-base-local:latest
    build:
      context: ../
      dockerfile: images/php/base/Dockerfile
      args:
        - ALPINE_VERSION=${ALPINE_VERSION?}
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER?}
        - APP_GROUP_ID=${APP_GROUP_ID?}
        - APP_GROUP_NAME=${APP_GROUP_NAME?}
        - APP_USER_ID=${APP_USER_ID?}
        - APP_USER_NAME=${APP_USER_NAME?}
        - COMPOSER_VERSION=${COMPOSER_VERSION?}
        - ENV=local
        - TARGET_PHP_VERSION=8.1
      target: local
